name: Deploy to production server
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9.0]
    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
      NEXT_PUBLIC_SERVER_URL: "https://ashandglory.marticongost.cat"
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build
      - run: mkdir ~/.ssh
      - run: echo "$SSH_KEY" >> ~/.ssh/github-action
      - run: chmod 400 ~/.ssh/github-action
      - run: echo -e "Host vps\n\tUser root\n\tHostname marticongost.cat\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
      - run: rsync -re ssh ./out/ vps:/var/www/ash-and-glory --delete
